---
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

env:
  global:
    - AWS_REGION='eu-west-1'
    - TF_VAR_region=${AWS_REGION}
    - TF_WARN_OUTPUT_ERRORS=1

install:
  # Install the latest version of terraform with ansible
  - sudo pip install ansible
  - sudo ansible-galaxy install diodonfrost.terraform && sudo ln -s ~/.ansible/roles/diodonfrost.terraform ~/.ansible/roles/ansible-role-terraform
  - sudo ansible-pull -U https://github.com/diodonfrost/ansible-role-terraform tests/test.yml

before_script:
  - terraform -version

script:
  # Download Terraform requirements
  - terraform init

  # Rewrites config files to canonical format
  - terraform fmt -check=true

  # Test Terraform module
  - >
    terraform validate \
      -var "region=${AWS_REGION}" \
      -var "name=nuke-all" \
      -var "cloudwatch_schedule_expression=cron(0 4 ? * MON-FRI *)" \
      -var "exclude_resources=glacier,eip,rds" \
      -var "older_than=14d"

  # Test Terraform fixture example
  - cd examples/test_fixture
  - terraform init
  - terraform fmt -check=true
  - terraform validate
  - terraform -v
